---
output: html_document
editor:
    mode: source
editor_options: 
  chunk_output_type: console
---

# Introducción {.unnumbered}

Esta página contiene el material utilizado durante el **Curso Roc: Análisis de datos de eBird utilizando R.**

El curso consta de 4 módulos:

1\. [Introducción al entorno R en el contexto de eBird](intror.qmd)

2\. [Buenas prácticas para el uso de datos de eBird](ebird.qmd): introduction to the eBird Basic Dataset (EBD), challenges associated with using eBird data for analysis, and best practices for preparing eBird data for modeling.

3\. [Modelamiento de distribución y abundancia relativa](distabund): tasas de encuentro, abundancia relativa y ejemplos y aplicaciones prácticas usando distribución y abundancia.

4\. **Usos y aplicaciones de productos Estados y Tendencias**: descarga de productos de Estados y Tendencias, carga de datos en R y su uso para una variedad de aplicaciones.

## Configuración {#sec-intro-config}

Este cruso está pensado para ser interactivo. Todos los ejemplos están escritos en el lenguaje de programación R, y el instructor los irá resolviendo en tiempo real. Recomendamos seguir la clase seguirlo escribiendo el mismo código en su computador. Para evitar retrasos innecesarios, siga estas instrucciones de configuración antes del curso:

1.  [Crea una cuenta de eBird](https://secure.birds.cornell.edu/cassso/account/create) si aún no tiene una y solicita acceso a los datos crudos de eBird y a los productos de Estados y Tendencias:
    -   [Solicita acceso al eBird Basic Dataset (EBD)](https://ebird.org/data/download).
    -   [Solicita acceso a los productos de Estados y Tendencias](https://science.ebird.org/en/status-and-trends/download-data)
2.  [Descarga](https://cloud.r-project.org/) e instala la última versión de R. **Se requiere la versión 4.0.0 o posterior de R para poder seguir este curso**
3.  [Descarga](https://posit.co/download/rstudio-desktop/#download) e instala la última versión de RStudio. RStudio no es necesario para este taller; sin embargo, los instructores lo utilizarán y es posible que te resulte más fácil seguir el curso si trabajas en el mismo entorno.
4.   Los ejercicios de este curso utilizan varios paquetes de R. Para instalar todos los paquetes necesarios, ejecute el siguiente código

```{r}
#| label: intro-setup-packages
#| eval: false
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("ebird/ebird-best-practices")
```

5.  Asegúrate de que todos los paquetes estén actualizados a sus versiones más recientes haciendo clic en el botón Actualizar de la pestaña Paquetes en RStudio.
6.  Descarga el [paquete de datos](https://drive.google.com/drive/folders/1GgarYMegw1CLf35AKu89EHQyXqoBbuiJ?usp=share_link) que utilizaremos en este curso.

## Tutorial de configuración {#sec-tutorial-config}

Hemos creado un [video](https://www.youtube.com/watch?v=SLbjGBjgj_w) introductorio explicando los pasos a seguir para la descarga e instalación de todos los requerimientos del curso.

{{< video https://www.youtube.com/watch?v=SLbjGBjgj_w >}}
